aiminder:
  server:
    url: ${SERVER_HOST}
  client:
    url: ${CLIENT_HOST}
  cookie:
    domain: ""
    same-site: None
    http-only: true
    secure: true
  security:
    permit-paths:
      - /api/actuator/**
      - /api/swagger-ui.html
      - /api/swagger-ui/**
      - /api/v3/api-docs
      - /api/v3/api-docs.yaml
      - /api/v3/api-docs/**
      - /login/oauth2/**
      - /oauth2/**
    allow-origin-patterns:
      - http://localhost
      - http://localhost:*
      - ${CLIENT_HOST}
    allowed-redirect-hosts:
      - dev.aiminder.click
      - localhost
    default-redirect-base-url: https://dev.aiminder.click

spring:
  flyway:
    url: jdbc:postgresql://aiminder-database/aiminderdb
    locations: classpath:/db/migration
    user: aiminder
    password: aiminder

logging:
  level:
    root: info
    ai.aiminder: debug
    org.springframework.security: debug
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql:
      QUERY: debug
      PARAM: debug
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true
  api-docs:
    path: /api/v3/api-docs
    enabled: true

server:
  forward-headers-strategy: framework
