aiminder:
  scheduler:
    feedback:
      enabled: false
  jwt:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
  cookie:
    domain: ${COOKIE_DOMAIN}
    same-site: ${COOKIE_SAME_SITE}
    http-only: ${COOKIE_HTTP_ONLY}
    secure: ${COOKIE_SECURE}
  image:
    upload-dir: ./uploads/images
    max-file-size: 5242880
    allowed-types: image/jpeg,image/png,image/gif,image/webp

spring:
  r2dbc:
    protocol: r2dbc
    driver: postgresql
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:5432}
    database: ${DATABASE_NAME:aiminderdb}
    username: ${DATABASE_USERNAME:aiminder}
    password: ${DATABASE_PASSWORD:aiminder}
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/aiminderdb}
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
  profiles:
    default: openai, local
  webflux:
    multipart:
      max-in-memory-size: 1MB
      max-disk-usage-per-part: 5MB
      max-parts: 1
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
            redirect-uri: ${aiminder.server.url}/login/oauth2/code/google

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            redirect-uri: ${aiminder.server.url}/login/oauth2/code/kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
