aiminder:
  scheduler:
    feedback:
      enabled: false
  server:
    url: http://localhost:8080
  client:
    url: http://localhost:3000
  cookie:
    domain: ""
    same-site: Lax
    http-only: true
    secure: false
  security:
    permit-paths:
      - /api/actuator/**
      - /api/swagger-ui.html
      - /api/swagger-ui/**
      - /api/v3/api-docs
      - /api/v3/api-docs.yaml
      - /api/v3/api-docs/**
      - /login/oauth2/**
      - /oauth2/**
      - /favicon.ico
    allow-origin-patterns:
      - http://localhost:*
    allowed-redirect-hosts:
      - localhost
      - 127.0.0.1
    default-redirect-base-url: http://localhost:3000

spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/aiminderdb
    locations: classpath:/db/migration
    user: aiminder
    password: aiminder

logging:
  level:
    root: info
    ai.aiminder: debug
    org.springframework.security: debug
    io.r2dbc.postgresql:
      QUERY: debug
      PARAM: debug

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true
  api-docs:
    path: /api/v3/api-docs
    enabled: true

server:
  forward-headers-strategy: framework
